### ISSUE TITLE
Merge not working

### ISSUE THREAD

**Issue by czKKill** [L3tum/KCDModMerger#2]
After launching the Mod Merger 4 conflicts are detected, but after I press Merge button no zzz_merge folder is created and ModMerger folder contains only empty folders. Am I doing something wrong..?

Log file: [KCDModMerger.log](https://github.com/L3tum/KCDModMerger/files/1868871/KCDModMerger.log)
Mods folder:
![mods](https://user-images.githubusercontent.com/35238696/38208318-fcea518c-36b0-11e8-9a43-adc77b6ace22.png)

**Comment by L3tum** [comment]
Thanks for the information!

Should be fixed in the newest version. Butchered up the no-manifest-name handling

**Comment by czKKill** [comment]
It's working now, thanks!
